### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by carlbordum** [theelous3/multio#10]

**Comment by carlwgeorge** [comment]
I would like to package this software in Fedora, but I can't if it doesn't have a license.  The `setup.py` file [appears to indicate the intention of using the MIT license](https://github.com/theelous3/multio/blob/38386d62e1c3cc8c366064fbbac5695da17e1c1b/setup.py#L13), but a LICENSE file is still needed.  I would send a pull request to add it but I don't know who the copyright holder should be.

https://choosealicense.com/licenses/mit/

**Comment by theelous3** [comment]
Done.

**Comment by carlwgeorge** [comment]
Thanks!

**Comment by raylu** [comment]
(done in 418e504d531d8a81056e430124332796da7ac00f)

I think it's almost always spelled "license" in modern english (the file is `LICENCE.txt`)

**Comment by theelous3** [comment]
American English is not the canonical modern English rayray!
