### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by carlwgeorge** [theelous3/multio#20]
Please tag the previous and future releases of this software.  [Sometimes the commit messages make it apparent](https://github.com/theelous3/multio/commit/38386d62e1c3cc8c366064fbbac5695da17e1c1b), but [sometimes they don't](https://github.com/theelous3/multio/commit/1e9e281d59b8736172529db2e8a929a677b4a6d4).  Using tags makes it unambiguous, and makes things easier on distro packagers like myself.

**Comment by theelous3** [comment]
Sure thing.

**Comment by carlwgeorge** [comment]
Thanks!

**Comment by raylu** [comment]
did you run `git push --tags`? I don't see any https://github.com/theelous3/multio/tags

**Comment by theelous3** [comment]
When I'm home :D

**Comment by carlwgeorge** [comment]
I'm still not seeing any tags, could you take another look?

**Comment by theelous3** [comment]
There ya go. Threw on a quick one there.
